/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/logs/': RouteRecordInfo<'/logs/', '/logs', Record<never, never>, Record<never, never>>,
    '/logs/week/[week]': RouteRecordInfo<'/logs/week/[week]', '/logs/week/:week', { week: ParamValue<true> }, { week: ParamValue<false> }>,
    '/logs/weekly': RouteRecordInfo<'/logs/weekly', '/logs/weekly', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/loginPage': RouteRecordInfo<'/loginPage', '/loginPage', Record<never, never>, Record<never, never>>,
    '/logs/daily': RouteRecordInfo<'/logs/daily', '/logs/daily', Record<never, never>, Record<never, never>>,
    '/logs/student': RouteRecordInfo<'/logs/student', '/logs/student', Record<never, never>, Record<never, never>>,
    '/logs/weekly': RouteRecordInfo<'/logs/weekly', '/logs/weekly', Record<never, never>, Record<never, never>>,
  }
}
